# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: "1000"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          release_name: Release ${{ steps.gitversion.outputs.semVer }}
          draft: false
          prerelease: false
          
      - name: Remove .git folder
        uses: JesseTG/rm@v1.0.0
        with:
          path: .git
          
      - name: Remove .github folder
        uses: JesseTG/rm@v1.0.0
        with:
          path: .github
          
      - name: Remove GitVersion.yml
        uses: JesseTG/rm@v1.0.0
        with:
          path: GitVersion.yml

      - name: Set version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: version
          VALUE: ${{ steps.gitversion.outputs.semVer }}
          FILE: module.json

      - name: Set download URL
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: download
          VALUE: https://github.com/thenkles/vtt-macro-folders/releases/download/${{ steps.gitversion.outputs.semVer }}/MacroFolders-${{ steps.gitversion.outputs.semVer }}.zip
          FILE: module.json

      - name: Set manifest URL
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: manifest
          VALUE: https://github.com/thenkles/vtt-macro-folders/releases/download/${{ steps.gitversion.outputs.semVer }}/module.json
          FILE: module.json
          
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: MacroRunner-${{ steps.gitversion.outputs.semVer }}.zip
          recursive: true
    
      - name: Upload zipped files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MacroFolders-${{ steps.gitversion.outputs.semVer }}.zip
          asset_name: MacroFolders-${{ steps.gitversion.outputs.semVer }}.zip
          asset_content_type: application/zip

      - name: Upload manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module.json
          asset_name: module.json
          asset_content_type: application/json
